# Os dados deste Secret sao protegidos EM REPOUSO no etcd pela EncryptionConfiguration
apiVersion: v1
kind: Secret
metadata:
  name: hora-marcada-secrets
  namespace: hora-marcada
type: Opaque
stringData:
  JWT_SECRET: "hora-marcada-dev-secret-trocar-em-producao"
  ADMIN_PASSWORD: "Admin@12345"
  POSTGRES_AUTH_PASSWORD: "authpass"
  POSTGRES_SCHED_PASSWORD: "schedpass"
  AUTH_DATABASE_URL: "postgresql+psycopg://auth:authpass@users-db:5432/usersdb"
  SCHED_DATABASE_URL: "postgresql+psycopg://sched:schedpass@appointments-db:5432/appointmentsdb"
